spring:
  cloud:
    kubernetes:
      enabled: true
      discovery:
        enabled: true
        all-namespaces: false
        service-labels:
          spring-boot: true
eureka:
  client:
    enabled: false